# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 382ad1fbce3e0716b214589b3293bf2d80881cc974e64c24f46ffec8a00ca3494c53883a908e86e0ac48253d1a685dfb8e61ff18460c6661ef54631f9baf8cbb

test:
  secret_key_base: 4d52efffefe1d054d6cee1c51971a5a458eb0f5fbd4b0a37b258d56605e561361679417d21431d5b71af7e90b5caeddc8440fee75d5d2a513754297e11f6b6ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
