Movie.delete_all

Movie.create!( mpaa_rating: "R", release_date: "1994-09-14", title: "The Shawshank Redemption")
Movie.create!( mpaa_rating: "R", release_date: "1998-07-24", title: "Saving Private Ryan")
Movie.create!( mpaa_rating: "R", release_date: "2010-09-17", title: "Incendies")
Movie.create!( mpaa_rating: "R", release_date: "1974-12-20", title: "The Godfather: Part II")
Movie.create!( mpaa_rating: "R", release_date: "1972-03-15", title: "The Godfather")
Movie.create!( mpaa_rating: "R", release_date: "2010-12-02", title: "Black Swan")
Movie.create!( mpaa_rating: "R", release_date: "2009-09-08", title: "Pandorum")
Movie.create!( mpaa_rating: "R", release_date: "2008-12-12", title: "Ip Man")
Movie.create!( mpaa_rating: "R", release_date: "2010-02-18", title: "Shutter Island")
Movie.create!( mpaa_rating: "R", release_date: "2008-10-10", title: "The Hurt Locker")
Movie.create!( mpaa_rating: "R", release_date: "2010-09-06", title: "The King's Speech")
Movie.create!( mpaa_rating: "R", release_date: "2009-12-03", title: "Zombieland")
Movie.create!( mpaa_rating: "R", release_date: "2010-08-03", title: "The Expendables")
Movie.create!( mpaa_rating: "R", release_date: "1980-05-22", title: "The Shining")
Movie.create!( mpaa_rating: "R", release_date: "2009-06-05", title: "The Hangover")
Movie.create!( mpaa_rating: "R", release_date: "2009-08-13", title: "District 9")
Movie.create!( mpaa_rating: "R", release_date: "2010-03-11", title: "Green Zone")
Movie.create!( mpaa_rating: "R", release_date: "2010-10-01", title: "Let Me In")
Movie.create!( mpaa_rating: "R", release_date: "2010-01-14", title: "The Book of Eli")
Movie.create!( mpaa_rating: "R", release_date: "2009-10-15", title: "Law Abiding Citizen")
Movie.create!( release_date: "2004-05-13", title: "Troy", mpaa_rating: "R")
Movie.create!( release_date: "1972-03-15", title: "The Godfather", mpaa_rating: "R")
Movie.create!( release_date: "2010-12-02", title: "Black Swan", mpaa_rating: "R")
Movie.create!( release_date: "2008-12-12", title: "Ip Man", mpaa_rating: "R")
Movie.create!( release_date: "2011-07-21", title: "Friends with Benefits", mpaa_rating: "R")
Movie.create!( release_date: "2010-09-06", title: "The King's Speech", mpaa_rating: "R")
Movie.create!( release_date: "2011-08-12", title: "Final Destination 5", mpaa_rating: "R")
Movie.create!( release_date: "2011-03-25", title: "Sucker Punch", mpaa_rating: "R")
Movie.create!( release_date: "2010-10-01", title: "Let Me In", mpaa_rating: "R")
Movie.create!( release_date: "2011-05-25", title: "The Hangover Part II", mpaa_rating: "R")
Movie.create!( release_date: "1995-12-27", title: "Twelve Monkeys", mpaa_rating: "R")
Movie.create!( release_date: "2011-07-08", title: "Horrible Bosses", mpaa_rating: "R")
Movie.create!( release_date: "2011-11-02", title: "The Intouchables", mpaa_rating: "R")
Movie.create!( release_date: "1987-06-11", title: "Predator", mpaa_rating: "R")
Movie.create!( release_date: "2011-04-09", title: "A Lonely Place to Die", mpaa_rating: "R")
Movie.create!( release_date: "2011-09-16", title: "Drive", mpaa_rating: "R")
Movie.create!( release_date: "2011-04-11", title: "Scream 4", mpaa_rating: "R")
Movie.create!( release_date: "2011-04-28", title: "Bridesmaids", mpaa_rating: "R")
Movie.create!( release_date: "2011-08-19", title: "Conan the Barbarian", mpaa_rating: "R" )
Movie.create!( release_date: "2012-12-25", title: "Silver Linings Playbook", mpaa_rating: "R")
Movie.create!( release_date: "2012-03-12", title: "21 Jump Street", mpaa_rating: "R")
Movie.create!( release_date: "1999-10-14", title: "Fight Club", mpaa_rating: "R")
Movie.create!( release_date: "2012-04-12", title: "The Cabin in the Woods", mpaa_rating: "R")
Movie.create!( release_date: "2012-06-29", title: "Ted", mpaa_rating: "R")
Movie.create!( release_date: "2012-12-25", title: "Django Unchained", mpaa_rating: "R")
Movie.create!( release_date: "2012-04-06", title: "American Reunion", mpaa_rating: "R")
Movie.create!( release_date: "2011-07-21", title: "Friends with Benefits", mpaa_rating: "R")
Movie.create!( release_date: "2012-01-18", title: "Underworld: Awakening", mpaa_rating: "R")
Movie.create!( release_date: "2012-08-17", title: "The Expendables 2", mpaa_rating: "R")
Movie.create!( release_date: "2011-08-12", title: "Final Destination 5", mpaa_rating: "R")
Movie.create!( release_date: "2012-06-08", title: "Prometheus", mpaa_rating: "R")
Movie.create!( release_date: "2012-12-19", title: "Zero Dark Thirty", mpaa_rating: "R")
Movie.create!( release_date: "2007-10-19", title: "Gone Baby Gone", mpaa_rating: "R")
Movie.create!( release_date: "2012-03-29", title: "A Royal Affair", mpaa_rating: "R")
Movie.create!( release_date: "2012-10-12", title: "Argo", mpaa_rating: "R")
Movie.create!( release_date: "2012-07-06", title: "Savages", mpaa_rating: "R")
Movie.create!( release_date: "2012-08-22", title: "Hit and Run", mpaa_rating: "R")
Movie.create!( release_date: "2012-09-28", title: "Looper", mpaa_rating: "R")
Movie.create!( release_date: "2011-07-08", title: "Horrible Bosses", mpaa_rating: "R" )
Movie.create!( release_date: "2013-10-30", title: "12 Years a Slave", mpaa_rating: "R")
Movie.create!( release_date: "2012-12-25", title: "Silver Linings Playbook", mpaa_rating: "R")
Movie.create!( release_date: "2013-12-25", title: "The Wolf of Wall Street", mpaa_rating: "R")
Movie.create!( release_date: "2013-10-18", title: "Carrie", mpaa_rating: "R")
Movie.create!( release_date: "2012-04-12", title: "The Cabin in the Woods", mpaa_rating: "R")
Movie.create!( release_date: "2013-12-20", title: "American Hustle", mpaa_rating: "R")
Movie.create!( release_date: "2013-06-12", title: "This Is the End", mpaa_rating: "R")
Movie.create!( release_date: "2013-03-22", title: "Olympus Has Fallen", mpaa_rating: "R")
Movie.create!( release_date: "2013-12-24", title: "Lone Survivor", mpaa_rating: "R")
Movie.create!( release_date: "2013-10-18", title: "Escape Plan", mpaa_rating: "R")
Movie.create!( release_date: "2013-02-14", title: "A Good Day to Die Hard", mpaa_rating: "R")
Movie.create!( release_date: "2012-12-25", title: "Django Unchained", mpaa_rating: "R")
Movie.create!( release_date: "2013-06-21", title: "The Bling Ring", mpaa_rating: "R")
Movie.create!( release_date: "2013-07-19", title: "The Conjuring", mpaa_rating: "R")
Movie.create!( release_date: "2013-07-19", title: "The World's End", mpaa_rating: "R")
Movie.create!( release_date: "2013-08-09", title: "Elysium", mpaa_rating: "R")
Movie.create!( release_date: "2013-09-27", title: "Rush", mpaa_rating: "R")
Movie.create!( release_date: "2013-09-02", title: "The Zero Theorem", mpaa_rating: "R")
Movie.create!( release_date: "2013-12-18", title: "Her", mpaa_rating: "R")
Movie.create!( release_date: "2012-12-19", title: "Zero Dark Thirty", mpaa_rating: "R" )
Movie.create!( release_date: "2014-10-17", title: "Birdman", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-10", title: "Whiplash", mpaa_rating: "R")
Movie.create!( release_date: "2014-07-25", title: "Lucy", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-24", title: "John Wick", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-17", title: "Fury", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-03", title: "Gone Girl", mpaa_rating: "R")
Movie.create!( release_date: "2014-11-26", title: "Horrible Bosses 2", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-31", title: "Nightcrawler", mpaa_rating: "R")
Movie.create!( release_date: "2014-09-26", title: "The Equalizer", mpaa_rating: "R")
Movie.create!( release_date: "2014-07-11", title: "Boyhood", mpaa_rating: "R")
Movie.create!( release_date: "2014-12-25", title: "The Interview", mpaa_rating: "R")
Movie.create!( release_date: "2014-09-19", title: "A Walk Among the Tombstones", mpaa_rating: "R")
Movie.create!( release_date: "2013-10-30", title: "12 Years a Slave", mpaa_rating: "R")
Movie.create!( release_date: "2014-08-27", title: "The November Man", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-10", title: "The Judge", mpaa_rating: "R")
Movie.create!( release_date: "2014-12-25", title: "American Sniper", mpaa_rating: "R")
Movie.create!( release_date: "2014-08-22", title: "Sin City: A Dame to Kill For", mpaa_rating: "R")
Movie.create!( release_date: "2014-03-07", title: "The Grand Budapest Hotel", mpaa_rating: "R")
Movie.create!( release_date: "2014-08-13", title: "Let's Be Cops", mpaa_rating: "R")
Movie.create!( release_date: "2013-12-25", title: "The Wolf of Wall Street", mpaa_rating: "R" )
Movie.create!( release_date: "2014-10-17", title: "Birdman", mpaa_rating: "R")
Movie.create!( release_date: "2015-02-13", title: "Fifty Shades of Grey", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-10", title: "Whiplash", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-24", title: "John Wick", mpaa_rating: "R")
Movie.create!( release_date: "2015-01-16", title: "Vice", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-17", title: "Fury", mpaa_rating: "R")
Movie.create!( release_date: "2014-11-26", title: "Horrible Bosses 2", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-31", title: "Nightcrawler", mpaa_rating: "R")
Movie.create!( release_date: "2014-09-26", title: "The Equalizer", mpaa_rating: "R")
Movie.create!( release_date: "2015-02-13", title: "Kingsman: The Secret Service", mpaa_rating: "R")
Movie.create!( release_date: "2014-12-25", title: "The Interview", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-10", title: "The Judge", mpaa_rating: "R")
Movie.create!( release_date: "2015-01-30", title: "Wild Card", mpaa_rating: "R")
Movie.create!( release_date: "2014-12-25", title: "American Sniper", mpaa_rating: "R")
Movie.create!( release_date: "2015-02-27", title: "Focus", mpaa_rating: "R")
Movie.create!( release_date: "2014-08-13", title: "Let's Be Cops", mpaa_rating: "R")
Movie.create!( release_date: "2014-09-12", title: "The Drop", mpaa_rating: "R")
Movie.create!( release_date: "2014-11-14", title: "Foxcatcher", mpaa_rating: "R")
Movie.create!( release_date: "2014-12-12", title: "Inherent Vice", mpaa_rating: "R")
Movie.create!( release_date: "2014-10-09", title: "Autómata", mpaa_rating: "R" )
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-12-02", title: "The Lost Legion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-09-03", title: "Maintenant Ou Jamais")
Movie.create!( mpaa_rating: "NC-17", release_date: "2003-12-09", title: "The Dreamers")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-05-25", title: "The Normal Heart")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-10-09", title: "Blue Is the Warmest Color")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-01-10", title: "The Truth About Emanuel")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-12-02", title: "The Lost Legion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-09-03", title: "Maintenant Ou Jamais")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-10-17", title: "Lasa & Zabala")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-10-01", title: "Sibling Sex Stories 2")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-05-22", title: "My Sweet Pepper Land")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-02-14", title: "Lucky Bastard")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-10-05", title: "After Death")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-02-01", title: "Bingo Night")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-07-01", title: "Haunting of Cellblock 11")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-10-09", title: "Blue Is the Warmest Color")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-01-10", title: "The Truth About Emanuel")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-09-27", title: "Dead Mine")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-29", title: "Zombie Apocalypse")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-09-09", title: "Elles")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-12-31", title: "Jailbait")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-05-22", title: "My Sweet Pepper Land")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-12-10", title: "The Falls: Testament Of Love")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-07-31", title: "Eco Migrants: The Case of Bhola Island")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-01-30", title: "House of Last Things")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-10-25", title: "Collider")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-03-01", title: "Roadside")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-03-17", title: "23 Minutes To Sunrise")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-04-25", title: "Axe Giant - The Wrath of Paul Bunyan")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-06-18", title: "Muirhouse")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-12-02", title: "Shame")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-21", title: "Retreat")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-01-11", title: "Cold Fusion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-09-27", title: "Dead Mine")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-29", title: "Zombie Apocalypse")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-09-09", title: "Elles")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-05-16", title: "Daddy Did The Babysitter")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-07-11", title: "UFC on Fuel TV: Munoz vs. Weidman")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-10-05", title: "After Death")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-09-25", title: "Porkchop II: Rise of the Rind")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-12-22", title: "Rihanna - 777 Tour - Live From London")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-10-09", title: "Life Is Not a Fairytale: The Fantasia Barrino Story")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-08-31", title: "Scream: The Giallo Cut")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-08-01", title: "Burning Folk: A Road Movie")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-07-06", title: "Dance Fu")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-04-27", title: "Innocent But Nasty")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-11-09", title: "The Brazen Bull")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-12-02", title: "Shame")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-06-16", title: "A Serbian Film")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-21", title: "Retreat")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-09-14", title: "Sinners and Saints")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-01-11", title: "Cold Fusion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-29", title: "Zombie Apocalypse")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-09-09", title: "Elles")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-11-01", title: "Warren Ellis: Captured Ghosts")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-07-30", title: "Alien vs. Ninja")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-12-01", title: "Lavell Crawford: Can a Brother Get Some Love?")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-06-11", title: "UFC 131: Dos Santos vs. Carwin")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-03-23", title: "Russell Peters: The Green Card Tour")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-07-20", title: "The Dead Inside")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-04-30", title: "UFC 129: The Prelims")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-06-16", title: "A Serbian Film")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-09-14", title: "Sinners and Saints")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-07-30", title: "Alien vs. Ninja")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-10-07", title: "L.A. Zombie")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-08-21", title: "Strikeforce: Houston")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-11-22", title: "Perversion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-10-09", title: "Strikeforce: San Jose")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-12-05", title: "Bad Company")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-11-09", title: "The Brazen Bull")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-08-10", title: "Nightmare Alley")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-06-23", title: "The Stranger in Us")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-04-23", title: "Brilliantlove")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-01-01", title: "The Last Vampire On Earth")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-12-02", title: "The Lost Legion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-09-03", title: "Maintenant Ou Jamais")
Movie.create!( mpaa_rating: "NC-17", release_date: "2003-12-09", title: "The Dreamers")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-05-25", title: "The Normal Heart")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-10-09", title: "Blue Is the Warmest Color")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-01-10", title: "The Truth About Emanuel")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-12-02", title: "The Lost Legion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-09-03", title: "Maintenant Ou Jamais")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-10-17", title: "Lasa & Zabala")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-10-01", title: "Sibling Sex Stories 2")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-05-22", title: "My Sweet Pepper Land")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-02-14", title: "Lucky Bastard")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-10-05", title: "After Death")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-02-01", title: "Bingo Night")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-07-01", title: "Haunting of Cellblock 11")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-10-09", title: "Blue Is the Warmest Color")
Movie.create!( mpaa_rating: "NC-17", release_date: "2014-01-10", title: "The Truth About Emanuel")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-09-27", title: "Dead Mine")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-29", title: "Zombie Apocalypse")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-09-09", title: "Elles")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-12-31", title: "Jailbait")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-05-22", title: "My Sweet Pepper Land")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-12-10", title: "The Falls: Testament Of Love")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-07-31", title: "Eco Migrants: The Case of Bhola Island")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-01-30", title: "House of Last Things")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-10-25", title: "Collider")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-03-01", title: "Roadside")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-03-17", title: "23 Minutes To Sunrise")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-04-25", title: "Axe Giant - The Wrath of Paul Bunyan")
Movie.create!( mpaa_rating: "NC-17", release_date: "2013-06-18", title: "Muirhouse")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-12-02", title: "Shame")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-21", title: "Retreat")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-01-11", title: "Cold Fusion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-09-27", title: "Dead Mine")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-29", title: "Zombie Apocalypse")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-09-09", title: "Elles")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-05-16", title: "Daddy Did The Babysitter")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-07-11", title: "UFC on Fuel TV: Munoz vs. Weidman")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-10-05", title: "After Death")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-09-25", title: "Porkchop II: Rise of the Rind")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-12-22", title: "Rihanna - 777 Tour - Live From London")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-10-09", title: "Life Is Not a Fairytale: The Fantasia Barrino Story")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-08-31", title: "Scream: The Giallo Cut")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-08-01", title: "Burning Folk: A Road Movie")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-07-06", title: "Dance Fu")
Movie.create!( mpaa_rating: "NC-17", release_date: "2012-04-27", title: "Innocent But Nasty")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-11-09", title: "The Brazen Bull")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-12-02", title: "Shame")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-06-16", title: "A Serbian Film")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-21", title: "Retreat")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-09-14", title: "Sinners and Saints")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-01-11", title: "Cold Fusion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-10-29", title: "Zombie Apocalypse")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-09-09", title: "Elles")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-11-01", title: "Warren Ellis: Captured Ghosts")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-07-30", title: "Alien vs. Ninja")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-12-01", title: "Lavell Crawford: Can a Brother Get Some Love?")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-06-11", title: "UFC 131: Dos Santos vs. Carwin")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-03-23", title: "Russell Peters: The Green Card Tour")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-07-20", title: "The Dead Inside")
Movie.create!( mpaa_rating: "NC-17", release_date: "2011-04-30", title: "UFC 129: The Prelims")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-06-16", title: "A Serbian Film")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-09-14", title: "Sinners and Saints")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-07-30", title: "Alien vs. Ninja")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-10-07", title: "L.A. Zombie")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-08-21", title: "Strikeforce: Houston")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-11-22", title: "Perversion")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-10-09", title: "Strikeforce: San Jose")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-12-05", title: "Bad Company")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-11-09", title: "The Brazen Bull")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-08-10", title: "Nightmare Alley")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-06-23", title: "The Stranger in Us")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-04-23", title: "Brilliantlove")
Movie.create!( mpaa_rating: "NC-17", release_date: "2010-01-01", title: "The Last Vampire On Earth")
Movie.create!( mpaa_rating: "PG-13", release_date: "2009-12-18", title: "Avatar")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-05-07", title: "Iron Man 2")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-07-16", title: "Inception")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-06-04", title: "Killers")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-08-06", title: "Step Up 3D")
Movie.create!( mpaa_rating: "PG-13", release_date: "2009-05-20", title: "Terminator Salvation")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-06-23", title: "Knight and Day")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-11-19", title: "Harry Potter and the Deathly Hallows: Part 1")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-07-23", title: "Salt")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-11-12", title: "Unstoppable")
Movie.create!( mpaa_rating: "PG-13", release_date: "2009-05-17", title: "Agora")
Movie.create!( mpaa_rating: "PG-13", release_date: "2009-09-24", title: "Surrogates")
Movie.create!( mpaa_rating: "PG-13", release_date: "2009-12-25", title: "Sherlock Holmes")
Movie.create!( mpaa_rating: "PG-13", release_date: "2009-11-20", title: "The Blind Side")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-04-08", title: "Date Night")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-10-14", title: "RED")
Movie.create!( mpaa_rating: "PG-13", release_date: "2009-06-26", title: "My Sister's Keeper")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-09-13", title: "Insidious")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-07-27", title: "Scott Pilgrim vs. the World")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-04-02", title: "Clash of the Titans")
Movie.create!( mpaa_rating: "PG-13", release_date: "2001-12-19", title: "The Lord of the Rings: The Fellowship of the Ring")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-03-08", title: "Battle: Los Angeles")
Movie.create!( mpaa_rating: "PG-13", release_date: "2008-09-25", title: "Taken")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-05-06", title: "Thor")
Movie.create!( mpaa_rating: "PG-13", release_date: "2003-12-01", title: "The Lord of the Rings: The Return of the King")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-07-22", title: "Captain America: The First Avenger")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-12-21", title: "Mission: Impossible - Ghost Protocol")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-05-11", title: "Pirates of the Caribbean: On Stranger Tides")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-08-26", title: "Colombiana")
Movie.create!( mpaa_rating: "PG-13", release_date: "2008-07-11", title: "Hellboy II: The Golden Army")
Movie.create!( mpaa_rating: "PG-13", release_date: "2010-11-12", title: "Unstoppable")
Movie.create!( mpaa_rating: "PG-13", release_date: "2009-05-17", title: "Agora")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-07-07", title: "Harry Potter and the Deathly Hallows: Part 2")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-10-28", title: "In Time")
Movie.create!( mpaa_rating: "PG-13", release_date: "1986-06-11", title: "Ferris Bueller's Day Off")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-01-13", title: "The Green Hornet")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-03-08", title: "Limitless")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-06-16", title: "Green Lantern")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-03-15", title: "Water for Elephants")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-08-04", title: "Rise of the Planet of the Apes")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-12-14", title: "The Hobbit: An Unexpected Journey")
Movie.create!( mpaa_rating: "PG-13", release_date: "1993-06-08", title: "Jurassic Park")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-07-20", title: "The Dark Knight Rises")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-05-04", title: "The Avengers")
Movie.create!( mpaa_rating: "PG-13", release_date: "1997-12-19", title: "Titanic")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-08-10", title: "The Bourne Legacy")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-07-26", title: "Step Up Revolution")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-12-21", title: "Mission: Impossible - Ghost Protocol")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-07-04", title: "The Amazing Spider-Man")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-08-26", title: "Colombiana")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-10-04", title: "Taken 2")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-11-16", title: "Lincoln")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-10-28", title: "In Time")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-04-12", title: "Lockout")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-08-03", title: "Total Recall")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-06-01", title: "Snow White and the Huntsman")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-03-08", title: "Limitless")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-05-18", title: "Battleship")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-03-23", title: "The Hunger Games")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-10-11", title: "The Impossible")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-05-24", title: "Fast & Furious 6")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-12-13", title: "The Hobbit: The Desolation of Smaug")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-11-22", title: "The Hunger Games: Catching Fire")
Movie.create!( mpaa_rating: "PG-13", release_date: "1993-06-08", title: "Jurassic Park")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-07-20", title: "The Dark Knight Rises")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-06-21", title: "World War Z")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-10-04", title: "Gravity")
Movie.create!( mpaa_rating: "PG-13", release_date: "2008-09-25", title: "Taken")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-05-31", title: "Now You See Me")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-05-16", title: "Star Trek Into Darkness")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-11-08", title: "Thor: The Dark World")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-06-14", title: "Man of Steel")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-05-03", title: "Iron Man 3")
Movie.create!( mpaa_rating: "PG-13", release_date: "2012-08-10", title: "The Bourne Legacy")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-10-11", title: "Captain Phillips")
Movie.create!( mpaa_rating: "PG-13", release_date: "2011-05-11", title: "Pirates of the Caribbean: On Stranger Tides")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-03-15", title: "The Incredible Burt Wonderstone")
Movie.create!( mpaa_rating: "PG-13", release_date: "2005-05-19", title: "Star Wars: Episode III - Revenge of the Sith")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-03-29", title: "G.I. Joe: Retaliation")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-11-08", title: "The Book Thief")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-12-17", title: "The Hobbit: The Battle of the Five Armies")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-11-14", title: "The Imitation Game")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-11-21", title: "The Hunger Games: Mockingjay - Part 1")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-11-05", title: "Interstellar")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-08-01", title: "Guardians of the Galaxy")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-10-03", title: "Dracula Untold")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-08-08", title: "Teenage Mutant Ninja Turtles")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-09-19", title: "The Maze Runner")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-11-26", title: "The Theory of Everything")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-11-14", title: "Dumb and Dumber To")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-04-04", title: "Captain America: The Winter Soldier")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-05-23", title: "X-Men: Days of Future Past")
Movie.create!( mpaa_rating: "PG-13", release_date: "2013-12-13", title: "The Hobbit: The Desolation of Smaug")
Movie.create!( mpaa_rating: "PG-13", release_date: "2015-02-06", title: "Seventh Son")
Movie.create!( mpaa_rating: "PG-13", release_date: "2015-01-09", title: "Taken 3")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-07-23", title: "Hercules")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-06-06", title: "Edge of Tomorrow")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-06-27", title: "Transformers: Age of Extinction")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-05-02", title: "The Amazing Spider-Man 2")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-07-11", title: "Dawn of the Planet of the Apes")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-12-17", title: "The Hobbit: The Battle of the Five Armies")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-11-14", title: "The Imitation Game")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-09-19", title: "The Maze Runner")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-11-26", title: "The Theory of Everything")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-11-14", title: "Dumb and Dumber To")
Movie.create!( mpaa_rating: "PG-13", release_date: "2015-02-06", title: "Seventh Son")
Movie.create!( mpaa_rating: "PG-13", release_date: "2015-01-09", title: "Taken 3")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-10-31", title: "St. Vincent")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-10-24", title: "Ouija")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-10-03", title: "Left Behind")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-12-25", title: "Selma")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-10-24", title: "Stonehearst Asylum")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-12-05", title: "Still Alice")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-12-25", title: "Big Eyes")
Movie.create!( mpaa_rating: "PG-13", release_date: "2015-01-30", title: "Project Almanac")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-12-25", title: "Unbroken")
Movie.create!( mpaa_rating: "PG-13", release_date: "2014-10-12", title: "Serena")
Movie.create!( mpaa_rating: "PG-13", release_date: "2015-02-27", title: "The Lazarus Effect")
Movie.create!( mpaa_rating: "PG-13", release_date: "2015-11-20", title: "The Hunger Games: Mockingjay - Part 2")
Movie.create!( mpaa_rating: "PG-13", release_date: "2015-03-20", title: "Tracers")
Movie.create!( mpaa_rating: "PG", release_date: "2014-11-07", title: "Big Hero 6")
Movie.create!( mpaa_rating: "PG", release_date: "2014-12-19", title: "Night at the Museum: Secret of the Tomb")
Movie.create!( mpaa_rating: "PG", release_date: "2014-12-19", title: "Annie")
Movie.create!( mpaa_rating: "PG", release_date: "2014-12-25", title: "Into the Woods")
Movie.create!( mpaa_rating: "PG", release_date: "2015-02-06", title: "The SpongeBob Movie: Sponge Out of Water")
Movie.create!( mpaa_rating: "PG", release_date: "2014-04-16", title: "Serial (Bad) Weddings")
Movie.create!( mpaa_rating: "PG", release_date: "2015-03-13", title: "Cinderella")
Movie.create!( mpaa_rating: "PG", release_date: "2015-01-27", title: "Justice League: Throne of Atlantis")
Movie.create!( mpaa_rating: "PG", release_date: "2014-10-17", title: "The Book of Life")
Movie.create!( mpaa_rating: "PG", release_date: "2014-11-28", title: "Paddington")
Movie.create!( mpaa_rating: "PG", release_date: "2014-10-10", title: "Alexander and the Terrible, Horrible, No Good, Very Bad Day")
Movie.create!( mpaa_rating: "PG", release_date: "2014-01-17", title: "The Nut Job")
Movie.create!( mpaa_rating: "PG", release_date: "2015-02-26", title: "The Second Best Exotic Marigold Hotel")
Movie.create!( mpaa_rating: "PG", release_date: "2015-03-04", title: "Shania: Still the One - Live from Vegas")
Movie.create!( mpaa_rating: "PG", release_date: "2015-02-20", title: "McFarland USA")
Movie.create!( mpaa_rating: "PG", release_date: "2014-08-22", title: "When the Game Stands Tall")
Movie.create!( mpaa_rating: "PG", release_date: "2013-12-29", title: "Minuscule: Valley of the Lost Ants")
Movie.create!( mpaa_rating: "PG", release_date: "2014-09-02", title: "Mostly Ghostly: Have You Met My Ghoulfriend?")
Movie.create!( mpaa_rating: "PG", release_date: "2015-01-25", title: "Away and Back")
Movie.create!( mpaa_rating: "PG", release_date: "2015-01-23", title: "Strange Magic")
Movie.create!( mpaa_rating: "PG", release_date: "2014-11-07", title: "Big Hero 6")
Movie.create!( mpaa_rating: "PG", release_date: "2014-12-19", title: "Night at the Museum: Secret of the Tomb")
Movie.create!( mpaa_rating: "PG", release_date: "2014-11-26", title: "Penguins of Madagascar")
Movie.create!( mpaa_rating: "PG", release_date: "2014-12-19", title: "Annie")
Movie.create!( mpaa_rating: "PG", release_date: "2014-02-07", title: "The Lego Movie")
Movie.create!( mpaa_rating: "PG", release_date: "2014-06-13", title: "How to Train Your Dragon 2")
Movie.create!( mpaa_rating: "PG", release_date: "2013-11-27", title: "Frozen")
Movie.create!( mpaa_rating: "PG", release_date: "2014-12-25", title: "Into the Woods")
Movie.create!( mpaa_rating: "PG", release_date: "2014-05-30", title: "Maleficent")
Movie.create!( mpaa_rating: "PG", release_date: "2014-09-26", title: "The Boxtrolls")
Movie.create!( mpaa_rating: "PG", release_date: "2014-07-18", title: "Planes: Fire & Rescue")
Movie.create!( mpaa_rating: "PG", release_date: "2014-04-16", title: "Serial (Bad) Weddings")
Movie.create!( mpaa_rating: "PG", release_date: "2013-11-01", title: "Free Birds")
Movie.create!( mpaa_rating: "PG", release_date: "2014-10-17", title: "The Book of Life")
Movie.create!( mpaa_rating: "PG", release_date: "2014-11-28", title: "Paddington")
Movie.create!( mpaa_rating: "PG", release_date: "2011-10-28", title: "Puss in Boots")
Movie.create!( mpaa_rating: "PG", release_date: "2014-10-10", title: "Alexander and the Terrible, Horrible, No Good, Very Bad Day")
Movie.create!( mpaa_rating: "PG", release_date: "2013-12-25", title: "The Secret Life of Walter Mitty")
Movie.create!( mpaa_rating: "PG", release_date: "2014-03-07", title: "Mr. Peabody & Sherman")
Movie.create!( mpaa_rating: "PG", release_date: "2014-01-17", title: "The Nut Job")
Movie.create!( mpaa_rating: "PG", release_date: "2012-11-21", title: "Life of Pi")
Movie.create!( mpaa_rating: "PG", release_date: "2013-11-27", title: "Frozen")
Movie.create!( mpaa_rating: "PG", release_date: "2013-08-07", title: "Percy Jackson: Sea of Monsters")
Movie.create!( mpaa_rating: "PG", release_date: "2013-07-02", title: "Despicable Me 2")
Movie.create!( mpaa_rating: "PG", release_date: "2013-05-24", title: "Epic")
Movie.create!( mpaa_rating: "PG", release_date: "2013-11-01", title: "Free Birds")
Movie.create!( mpaa_rating: "PG", release_date: "2012-09-27", title: "Hotel Transylvania")
Movie.create!( mpaa_rating: "PG", release_date: "2013-03-08", title: "Oz: The Great and Powerful")
Movie.create!( mpaa_rating: "PG", release_date: "2013-12-25", title: "The Secret Life of Walter Mitty")
Movie.create!( mpaa_rating: "PG", release_date: "2012-08-31", title: "Tad, the Lost Explorer")
Movie.create!( mpaa_rating: "PG", release_date: "2010-03-05", title: "How to Train Your Dragon")
Movie.create!( mpaa_rating: "PG", release_date: "2013-09-27", title: "Cloudy with a Chance of Meatballs 2")
Movie.create!( mpaa_rating: "PG", release_date: "2013-12-25", title: "The 100-Year-Old Man Who Climbed Out the Window and Disappeared")
Movie.create!( mpaa_rating: "PG", release_date: "2012-11-01", title: "Wreck-It Ralph")
Movie.create!( mpaa_rating: "PG", release_date: "2013-11-23", title: "The Tale of the Princess Kaguya")
Movie.create!( mpaa_rating: "PG", release_date: "2012-08-17", title: "ParaNorman")
Movie.create!( mpaa_rating: "PG", release_date: "2012-10-12", title: "Here Comes the Boom")
Movie.create!( mpaa_rating: "PG", release_date: "2013-03-21", title: "The Croods")
Movie.create!( mpaa_rating: "PG", release_date: "2013-08-30", title: "One Direction: This Is Us")
Movie.create!( mpaa_rating: "PG", release_date: "2013-07-19", title: "Turbo")
Movie.create!( mpaa_rating: "PG", release_date: "2012-11-21", title: "Life of Pi")
Movie.create!( mpaa_rating: "PG", release_date: "1975-06-19", title: "Jaws")
Movie.create!( mpaa_rating: "PG", release_date: "2012-09-27", title: "Hotel Transylvania")
Movie.create!( mpaa_rating: "PG", release_date: "2012-07-13", title: "Ice Age: Continental Drift")
Movie.create!( mpaa_rating: "PG", release_date: "2011-10-28", title: "Puss in Boots")
Movie.create!( mpaa_rating: "PG", release_date: "2012-08-10", title: "Brave")
Movie.create!( mpaa_rating: "PG", release_date: "2012-02-10", title: "Journey 2: The Mysterious Island")
Movie.create!( mpaa_rating: "PG", release_date: "2012-08-31", title: "Tad, the Lost Explorer")
Movie.create!( mpaa_rating: "PG", release_date: "2012-11-01", title: "Wreck-It Ralph")
Movie.create!( mpaa_rating: "PG", release_date: "2011-11-17", title: "Happy Feet Two")
Movie.create!( mpaa_rating: "PG", release_date: "2011-12-20", title: "The Adventures of Tintin")
Movie.create!( mpaa_rating: "PG", release_date: "2012-03-01", title: "The Lorax")
Movie.create!( mpaa_rating: "PG", release_date: "2012-06-08", title: "Madagascar 3: Europe's Most Wanted")
Movie.create!( mpaa_rating: "PG", release_date: "2012-08-17", title: "ParaNorman")
Movie.create!( mpaa_rating: "PG", release_date: "2011-11-23", title: "Hugo")
Movie.create!( mpaa_rating: "PG", release_date: "2012-10-12", title: "Here Comes the Boom")
Movie.create!( mpaa_rating: "PG", release_date: "2010-03-19", title: "Diary of a Wimpy Kid")
Movie.create!( mpaa_rating: "PG", release_date: "2011-11-23", title: "The Muppets")
Movie.create!( mpaa_rating: "PG", release_date: "2011-12-23", title: "We Bought a Zoo")
Movie.create!( mpaa_rating: "PG", release_date: "2012-03-28", title: "The Pirates! In an Adventure with Scientists!")
Movie.create!( mpaa_rating: "PG", release_date: "2010-11-04", title: "Megamind")
Movie.create!( mpaa_rating: "PG", release_date: "2011-06-16", title: "Cars 2")
Movie.create!( mpaa_rating: "PG", release_date: "2011-10-28", title: "Puss in Boots")
Movie.create!( mpaa_rating: "PG", release_date: "2010-11-24", title: "Tangled")
Movie.create!( mpaa_rating: "PG", release_date: "2011-11-17", title: "Happy Feet Two")
Movie.create!( mpaa_rating: "PG", release_date: "2011-12-20", title: "The Adventures of Tintin")
Movie.create!( mpaa_rating: "PG", release_date: "2011-11-23", title: "Hugo")
Movie.create!( mpaa_rating: "PG", release_date: "2011-05-25", title: "Kung Fu Panda 2")
Movie.create!( mpaa_rating: "PG", release_date: "2010-12-16", title: "TRON: Legacy")
Movie.create!( mpaa_rating: "PG", release_date: "1990-03-02", title: "The Hunt for Red October")
Movie.create!( mpaa_rating: "PG", release_date: "2011-06-17", title: "Mr. Popper's Penguins")
Movie.create!( mpaa_rating: "PG", release_date: "2011-07-29", title: "The Smurfs")
Movie.create!( mpaa_rating: "PG", release_date: "2011-03-03", title: "Rango")
Movie.create!( mpaa_rating: "PG", release_date: "2011-11-23", title: "The Muppets")
Movie.create!( mpaa_rating: "PG", release_date: "2011-12-23", title: "We Bought a Zoo")
Movie.create!( mpaa_rating: "PG", release_date: "2010-12-10", title: "The Chronicles of Narnia: The Voyage of the Dawn Treader")
Movie.create!( mpaa_rating: "PG", release_date: "2011-11-10", title: "Arthur Christmas")
Movie.create!( mpaa_rating: "PG", release_date: "2009-10-22", title: "Astro Boy")
Movie.create!( mpaa_rating: "PG", release_date: "2011-11-11", title: "Jack and Jill")
Movie.create!( mpaa_rating: "PG", release_date: "2011-03-30", title: "Hop")
Movie.create!( mpaa_rating: "PG", release_date: "1964-09-17", title: "Goldfinger")
Movie.create!( mpaa_rating: "PG", release_date: "2010-11-04", title: "Megamind")
Movie.create!( mpaa_rating: "PG", release_date: "2010-06-30", title: "The Last Airbender")
Movie.create!( mpaa_rating: "PG", release_date: "2010-07-13", title: "The Sorcerer's Apprentice")
Movie.create!( mpaa_rating: "PG", release_date: "2010-02-11", title: "Percy Jackson & the Olympians: The Lightning Thief")
Movie.create!( mpaa_rating: "PG", release_date: "1984-10-26", title: "Amadeus")
Movie.create!( mpaa_rating: "PG", release_date: "2010-03-04", title: "Alice in Wonderland")
Movie.create!( mpaa_rating: "PG", release_date: "2010-07-08", title: "Despicable Me")
Movie.create!( mpaa_rating: "PG", release_date: "2010-11-24", title: "Tangled")
Movie.create!( mpaa_rating: "PG", release_date: "2009-11-19", title: "Planet 51")
Movie.create!( mpaa_rating: "PG", release_date: "2010-03-05", title: "How to Train Your Dragon")
Movie.create!( mpaa_rating: "PG", release_date: "2008-10-07", title: "City of Ember")
Movie.create!( mpaa_rating: "PG", release_date: "1942-11-26", title: "Casablanca")
Movie.create!( mpaa_rating: "PG", release_date: "2010-03-19", title: "Diary of a Wimpy Kid")
Movie.create!( mpaa_rating: "PG", release_date: "2010-05-16", title: "Shrek Forever After")
Movie.create!( mpaa_rating: "PG", release_date: "1962-10-05", title: "Dr. No")
Movie.create!( mpaa_rating: "PG", release_date: "2010-09-24", title: "Legend of the Guardians: The Owls of Ga'Hoole")
Movie.create!( mpaa_rating: "PG", release_date: "2009-11-13", title: "Fantastic Mr. Fox")
Movie.create!( mpaa_rating: "PG", release_date: "1990-05-25", title: "Back to the Future Part III")
Movie.create!( mpaa_rating: "PG", release_date: "2010-12-16", title: "TRON: Legacy")
Movie.create!( mpaa_rating: "G", release_date: "1991-11-12", title: "Beauty and the Beast")
Movie.create!( mpaa_rating: "G", release_date: "2010-06-17", title: "Toy Story 3")
Movie.create!( mpaa_rating: "G", release_date: "2008-07-19", title: "Ponyo")
Movie.create!( mpaa_rating: "G", release_date: "1939-08-25", title: "The Wizard of Oz")
Movie.create!( mpaa_rating: "G", release_date: "2008-10-27", title: "Tinker Bell")
Movie.create!( mpaa_rating: "G", release_date: "2010-07-16", title: "The Secret World of Arrietty")
Movie.create!( mpaa_rating: "G", release_date: "2009-09-30", title: "Little Nicholas")
Movie.create!( mpaa_rating: "G", release_date: "2009-12-10", title: "The Princess and the Frog")
Movie.create!( mpaa_rating: "G", release_date: "1939-12-15", title: "Gone with the Wind")
Movie.create!( mpaa_rating: "G", release_date: "2009-01-01", title: "Hachi: A Dog's Tale")
Movie.create!( mpaa_rating: "G", release_date: "2010-09-14", title: "Barbie: A Fashion Fairytale")
Movie.create!( mpaa_rating: "G", release_date: "2010-03-01", title: "Barbie in A Mermaid Tale")
Movie.create!( mpaa_rating: "G", release_date: "2010-09-21", title: "Tinker Bell and the Great Fairy Rescue")
Movie.create!( mpaa_rating: "G", release_date: "2009-12-25", title: "The Gruffalo")
Movie.create!( mpaa_rating: "G", release_date: "2010-01-01", title: "LEGO: The Adventures of Clutch Powers")
Movie.create!( mpaa_rating: "G", release_date: "2010-12-13", title: "Despicable Me: Banana")
Movie.create!( mpaa_rating: "G", release_date: "2010-07-23", title: "Ramona and Beezus")
Movie.create!( mpaa_rating: "G", release_date: "2010-10-13", title: "Arthur 3: The War of the Two Worlds")
Movie.create!( mpaa_rating: "G", release_date: "2010-10-24", title: "The Good Witch's Gift")
Movie.create!( mpaa_rating: "G", release_date: "2010-12-13", title: "Despicable Me: Orientation Day")
Movie.create!( mpaa_rating: "G", release_date: "1991-11-12", title: "Beauty and the Beast")
Movie.create!( mpaa_rating: "G", release_date: "2011-04-15", title: "Rio")
Movie.create!( mpaa_rating: "G", release_date: "2011-11-24", title: "Ice Age: A Mammoth Christmas")
Movie.create!( mpaa_rating: "G", release_date: "2010-07-16", title: "The Secret World of Arrietty")
Movie.create!( mpaa_rating: "G", release_date: "2001-10-01", title: "Barbie in the Nutcracker")
Movie.create!( mpaa_rating: "G", release_date: "1951-07-26", title: "Alice in Wonderland")
Movie.create!( mpaa_rating: "G", release_date: "2011-07-14", title: "Winnie the Pooh")
Movie.create!( mpaa_rating: "G", release_date: "2011-06-24", title: "Toy Story Toons: Hawaiian Vacation")
Movie.create!( mpaa_rating: "G", release_date: "2011-01-13", title: "Gnomeo & Juliet")
Movie.create!( mpaa_rating: "G", release_date: "2011-08-11", title: "Barbie: Princess Charm School")
Movie.create!( mpaa_rating: "G", release_date: "2011-03-01", title: "Barbie: A Fairy Secret")
Movie.create!( mpaa_rating: "G", release_date: "2011-06-22", title: "La luna")
Movie.create!( mpaa_rating: "G", release_date: "2011-10-13", title: "Night of the Living Carrots")
Movie.create!( mpaa_rating: "G", release_date: "2011-11-15", title: "Dragons: Gift of the Night Fury")
Movie.create!( mpaa_rating: "G", release_date: "2011-09-20", title: "Spooky Buddies")
Movie.create!( mpaa_rating: "G", release_date: "2010-12-13", title: "Despicable Me: Banana")
Movie.create!( mpaa_rating: "G", release_date: "2010-07-23", title: "Ramona and Beezus")
Movie.create!( mpaa_rating: "G", release_date: "2010-10-13", title: "Arthur 3: The War of the Two Worlds")
Movie.create!( mpaa_rating: "G", release_date: "2011-12-14", title: "Alvin and the Chipmunks: Chipwrecked")
Movie.create!( mpaa_rating: "G", release_date: "2011-11-08", title: "Barbie: A Perfect Christmas")
Movie.create!( mpaa_rating: "G", release_date: "1994-05-20", title: "Aladdin 2: The Return of Jafar")
Movie.create!( mpaa_rating: "G", release_date: "2012-10-23", title: "Secret of the Wings")
Movie.create!( mpaa_rating: "G", release_date: "2011-11-24", title: "Ice Age: A Mammoth Christmas")
Movie.create!( mpaa_rating: "G", release_date: "2010-07-16", title: "The Secret World of Arrietty")
Movie.create!( mpaa_rating: "G", release_date: "2000-06-30", title: "Chicken Run")
Movie.create!( mpaa_rating: "G", release_date: "2003-09-28", title: "Barbie of Swan Lake")
Movie.create!( mpaa_rating: "G", release_date: "2012-11-02", title: "Paperman")
Movie.create!( mpaa_rating: "G", release_date: "2010-09-14", title: "Barbie: A Fashion Fairytale")
Movie.create!( mpaa_rating: "G", release_date: "2013-08-14", title: "Zambezia")
Movie.create!( mpaa_rating: "G", release_date: "2012-03-06", title: "Barbie in A Mermaid Tale 2")
Movie.create!( mpaa_rating: "G", release_date: "2012-01-13", title: "Tangled Ever After")
Movie.create!( mpaa_rating: "G", release_date: "2012-02-23", title: "Puss in Boots: The Three Diablos")
Movie.create!( mpaa_rating: "G", release_date: "2012-01-31", title: "Treasure Buddies")
Movie.create!( mpaa_rating: "G", release_date: "1987-08-28", title: "Babette's Feast")
Movie.create!( mpaa_rating: "G", release_date: "2011-03-01", title: "Barbie: A Fairy Secret")
Movie.create!( mpaa_rating: "G", release_date: "2011-06-22", title: "La luna")
Movie.create!( mpaa_rating: "G", release_date: "2011-11-15", title: "Dragons: Gift of the Night Fury")
Movie.create!( mpaa_rating: "G", release_date: "2012-09-30", title: "Barbie: The Princess & The Popstar")
Movie.create!( mpaa_rating: "G", release_date: "2010-10-13", title: "Arthur 3: The War of the Two Worlds")
Movie.create!( mpaa_rating: "G", release_date: "2011-12-14", title: "Alvin and the Chipmunks: Chipwrecked")
Movie.create!( mpaa_rating: "G", release_date: "2008-06-22", title: "WALL·E")
Movie.create!( mpaa_rating: "G", release_date: "2001-11-01", title: "Monsters, Inc.")
Movie.create!( mpaa_rating: "G", release_date: "2013-06-21", title: "Monsters University")
Movie.create!( mpaa_rating: "G", release_date: "2013-10-17", title: "Tarzan")
Movie.create!( mpaa_rating: "G", release_date: "2013-10-16", title: "The Young and Prodigious T.S. Spivet")
Movie.create!( mpaa_rating: "G", release_date: "2013-02-14", title: "Barbie in the Pink Shoes")
Movie.create!( mpaa_rating: "G", release_date: "2012-11-02", title: "Paperman")
Movie.create!( mpaa_rating: "G", release_date: "2013-08-14", title: "Zambezia")
Movie.create!( mpaa_rating: "G", release_date: "2013-08-27", title: "Super Buddies")
Movie.create!( mpaa_rating: "G", release_date: "2014-02-01", title: "Barbie: The Pearl Princess")
Movie.create!( mpaa_rating: "G", release_date: "2013-08-04", title: "Tom and Jerry's Giant Adventure")
Movie.create!( mpaa_rating: "G", release_date: "2013-10-25", title: "Khumba")
Movie.create!( mpaa_rating: "G", release_date: "2011-03-11", title: "Animals United")
Movie.create!( mpaa_rating: "G", release_date: "2013-05-30", title: "The Prodigal Returns - The Interview")
Movie.create!( mpaa_rating: "G", release_date: "2013-12-10", title: "Panic in the Mailroom")
Movie.create!( mpaa_rating: "G", release_date: "2013-10-08", title: "Alpha and Omega 2: A Howl-iday Adventure")
Movie.create!( mpaa_rating: "G", release_date: "2012-04-20", title: "DisneyNature Chimpanzee")
Movie.create!( mpaa_rating: "G", release_date: "2013-12-10", title: "Training Wheels")
Movie.create!( mpaa_rating: "G", release_date: "2012-09-14", title: "Partysaurus Rex")
Movie.create!( mpaa_rating: "G", release_date: "2013-12-10", title: "Puppy")
Movie.create!( mpaa_rating: "G", release_date: "2015-03-03", title: "Tinker Bell and the Legend of the NeverBeast")
Movie.create!( mpaa_rating: "G", release_date: "2014-04-11", title: "Rio 2")
Movie.create!( mpaa_rating: "G", release_date: "2014-11-07", title: "Feast")
Movie.create!( mpaa_rating: "G", release_date: "2014-11-26", title: "Asterix: The Land of the Gods")
Movie.create!( mpaa_rating: "G", release_date: "2014-02-25", title: "The Swan Princess: A Royal Family Tale")
Movie.create!( mpaa_rating: "G", release_date: "2014-04-01", title: "The Pirate Fairy")
Movie.create!( mpaa_rating: "G", release_date: "2013-10-17", title: "Tarzan")
Movie.create!( mpaa_rating: "G", release_date: "2014-12-02", title: "Toy Story That Time Forgot")
Movie.create!( mpaa_rating: "G", release_date: "2013-10-16", title: "The Young and Prodigious T.S. Spivet")
Movie.create!( mpaa_rating: "G", release_date: "2010-09-21", title: "Tinker Bell and the Great Fairy Rescue")
Movie.create!( mpaa_rating: "G", release_date: "2014-09-16", title: "Barbie and the Secret Door")
Movie.create!( mpaa_rating: "G", release_date: "1940-02-07", title: "Pinocchio")
Movie.create!( mpaa_rating: "G", release_date: "2014-02-01", title: "Barbie: The Pearl Princess")
Movie.create!( mpaa_rating: "G", release_date: "2013-08-04", title: "Tom and Jerry's Giant Adventure")
Movie.create!( mpaa_rating: "G", release_date: "2013-10-25", title: "Khumba")
Movie.create!( mpaa_rating: "G", release_date: "2014-09-27", title: "My Little Pony: Equestria Girls - Rainbow Rocks")
Movie.create!( mpaa_rating: "G", release_date: "2014-11-04", title: "Planes: Vitaminamulch Air Spectacular")
Movie.create!( mpaa_rating: "G", release_date: "2014-05-23", title: "Postman Pat: The Movie")
Movie.create!( mpaa_rating: "G", release_date: "2014-04-18", title: "Bears")
Movie.create!( mpaa_rating: "G", release_date: "2014-08-19", title: "Scooby-Doo! Frankencreepy")
Movie.create!( mpaa_rating: "G", release_date: "2015-03-03", title: "Tinker Bell and the Legend of the NeverBeast")
Movie.create!( mpaa_rating: "G", release_date: "2014-04-11", title: "Rio 2")
Movie.create!( mpaa_rating: "G", release_date: "2015-02-10", title: "LEGO DC Comics Super Heroes: Justice League vs. Bizarro League")
Movie.create!( mpaa_rating: "G", release_date: "2014-11-07", title: "Feast")
Movie.create!( mpaa_rating: "G", release_date: "2014-11-26", title: "Asterix: The Land of the Gods")
Movie.create!( mpaa_rating: "G", release_date: "2014-12-02", title: "Toy Story That Time Forgot")
Movie.create!( mpaa_rating: "G", release_date: "2013-10-16", title: "The Young and Prodigious T.S. Spivet")
Movie.create!( mpaa_rating: "G", release_date: "2014-05-23", title: "Postman Pat: The Movie")
Movie.create!( mpaa_rating: "G", release_date: "2015-02-23", title: "Cerrone")
Movie.create!( mpaa_rating: "G", release_date: "2015-04-03", title: "Walt Before Mickey")
Movie.create!( mpaa_rating: "G", release_date: "2015-02-04", title: "Florida Man")
Movie.create!( mpaa_rating: "G", release_date: "2015-02-03", title: "Doc Mcstuffins: Cuddle Me Lambie")
Movie.create!( mpaa_rating: "G", release_date: "2015-02-08", title: "Of Miracles And Men")
Movie.create!( mpaa_rating: "G", release_date: "2015-02-13", title: "The Ever After")

